In [1]:
import numpy as np

In [2]:
# Activation function (Sigmoid)
def Activation(x):
    return 1/(1+np.exp(-x))

In [3]:
def derivative(a):
    return a*(1-a)

In [4]:
# Input of  logic And gate
x=np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
x

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [13]:
# Expected output
y=np.array([[0],[0],[0],[1]])
y

array([[0],
       [0],
       [0],
       [1]])

In [14]:
# producing same number every time the program is initialised
np.random.seed(1)

In [15]:
# First random weight 
W1=np.random.random((3,4))

In [16]:
# Second random weight
W2=np.random.random((4,1))

In [17]:
for i in range(60000):
    first_layer=Activation(np.dot(x,W1))  
    second_layer=Activation(np.dot(first_layer,W2))
    abs_error= (y-second_layer)
    
    if(i % 10000) == 0:
        print('Error: ' + str(np.mean(np.abs(abs_error))))
    
    delta_Second_layer=abs_error * derivative(second_layer)
    error_first_layer=np.dot(delta_Second_layer, W2.T)
    delta_first_layer=error_first_layer * derivative(first_layer)
    
    W1 +=np.dot(x.T , delta_first_layer)
    W2 +=np.dot(first_layer.T,delta_Second_layer)
    

    

Error: 0.6295910214493052
Error: 0.00535384982479076
Error: 0.0036233054373464918
Error: 0.002893087735678118
Error: 0.0024690119026556994
Error: 0.0021846550073986917


In [18]:
print ("output after training:")
np.round(second_layer,2)

output after training:


array([[0.],
       [0.],
       [0.],
       [1.]])